language: c

compiler:
  - gcc
  - clang

arch:
  - amd64
  - ppc64le
addons:
  apt:
    packages:
      - cppcheck
      - clang-3.5
      
install:
  - export PYTHONUSERBASE=~/.local
  - easy_install --user scan-build
  - easy_install --user typing

script:
  - cppcheck --enable=all --error-exitcode=1 --inconclusive main.c fiche.c
  - make
  - scan-build --status-bugs make -B
